-- ============================================
-- RoomFinder Database Setup
-- ============================================
-- NOTE: This file documents the actual schema already in Supabase.
-- The queries below have ALREADY BEEN RUN.

-- 1. Create Profile/Users table (extends default auth)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  email TEXT,
  full_name TEXT,
  phone TEXT,
  role TEXT CHECK (role IN ('owner', 'finder')) DEFAULT 'finder'
);

-- NOTE: If your profiles table already exists, run this to add new columns:
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone TEXT;

-- 2. Create Rooms table
CREATE TABLE public.rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES public.profiles(id) NOT NULL,
  title TEXT NOT NULL,
  location TEXT NOT NULL,
  price NUMERIC NOT NULL,
  property_type TEXT NOT NULL,
  tenant_preference TEXT NOT NULL,
  contact_number TEXT,
  image_urls TEXT[], -- Array of image strings
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;

-- 4. Policy: Anyone can view rooms
CREATE POLICY "Public rooms are viewable by everyone"
ON public.rooms FOR SELECT USING (true);

-- 5. Policy: Owners can insert their own rooms
CREATE POLICY "Owners can insert their own rooms"
ON public.rooms FOR INSERT WITH CHECK (auth.uid() = owner_id);

-- 6. Policy: Owners can update their own rooms
CREATE POLICY "Owners can update their own rooms"
ON public.rooms FOR UPDATE USING (auth.uid() = owner_id);

-- 7. Policy: Owners can delete their own rooms
CREATE POLICY "Owners can delete their own rooms"
ON public.rooms FOR DELETE USING (auth.uid() = owner_id);

-- ============================================
-- RECOMMENDED: Run these additional queries
-- ============================================

-- Enable RLS on profiles table (recommended)
-- ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY "Users can view their own profile"
-- ON public.profiles FOR SELECT USING (auth.uid() = id);

-- CREATE POLICY "Users can insert their own profile"
-- ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- CREATE POLICY "Users can update their own profile"
-- ON public.profiles FOR UPDATE USING (auth.uid() = id);
